name: Lighthouse CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Generate Timestamp for Report
        id: timestamp
        run: echo "timestamp=$(date +'%Y_%m_%d_%H_%M_%S')" >> $GITHUB_ENV

      - name: Run Lighthouse Audit
        run: |
          mkdir -p lighthouse-results
          lhci autorun --upload.target=filesystem --upload.outputDir=./lighthouse-results || echo "Lighthouse CI failed"

      - name: Rename Lighthouse Results Directory
        run: mv ./lighthouse-results ./lighthouse-results-${{ env.timestamp }}

      - name: Prepare Reports Directory
        run: |
          mkdir -p reports
          mv ./lighthouse-results-${{ env.timestamp }} ./reports/${{ env.timestamp }}

      - name: Rename Lighthouse Report to index.html
        run: |
          cd ./reports/${{ env.timestamp }}
          mv *.report.html index.html

      - name: Extract Lighthouse Scores
        id: extract_scores
        run: |
          REPORT_FILE=$(ls ./reports/${{ env.timestamp }}/*.report.json)
          PERFORMANCE=$(jq '.categories.performance.score * 100' $REPORT_FILE)
          ACCESSIBILITY=$(jq '.categories.accessibility.score * 100' $REPORT_FILE)
          BEST_PRACTICES=$(jq '.categories["best-practices"].score * 100' $REPORT_FILE)
          SEO=$(jq '.categories.seo.score * 100' $REPORT_FILE)
          URL=$(jq -r '.finalUrl' $REPORT_FILE)

          echo "performance=$PERFORMANCE" >> $GITHUB_ENV
          echo "accessibility=$ACCESSIBILITY" >> $GITHUB_ENV
          echo "best_practices=$BEST_PRACTICES" >> $GITHUB_ENV
          echo "seo=$SEO" >> $GITHUB_ENV
          echo "url=$URL" >> $GITHUB_ENV

      - name: Update Summary Page
        run: |
          if [ ! -f reports/summary.html ]; then
            echo "<html><body><h1>Lighthouse Report Summary</h1><table border='1'>" > reports/summary.html
            echo "<tr><th>URL</th><th>Date and Time</th><th>Performance</th><th>Accessibility</th><th>Best Practices</th><th>SEO</th></tr>" >> reports/summary.html
          fi
          echo "<tr>" >> reports/summary.html
          echo "<td><a href='./${{ env.timestamp }}/index.html'>${{ env.url }}</a></td>" >> reports/summary.html
          echo "<td>${{ env.timestamp }}</td>" >> reports/summary.html
          echo "<td>${{ env.performance }}</td>" >> reports/summary.html
          echo "<td>${{ env.accessibility }}</td>" >> reports/summary.html
          echo "<td>${{ env.best_practices }}</td>" >> reports/summary.html
          echo "<td>${{ env.seo }}</td>" >> reports/summary.html
          echo "</tr>" >> reports/summary.html
          echo "</table></body></html>" >> reports/summary.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
